apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: dotnetapp
spec:
  ports:
    - port: 1433
  selector:
    app: dotnetapp
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: db
  labels:
    app: dotnetapp
spec:
  selector:
    matchLabels:
      app: dotnetapp
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dotnetapp
        tier: mysql
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:
      - name: docker-compose-dotnet-core-and-mssql-db
        image: 381492085613.dkr.ecr.us-east-1.amazonaws.com/demo:docker-compose-dotnet-core-and-mssql-db
        env:
        - name: MSSQL_PID
          value: "Express"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD 
