apiVersion: v1
kind: Service
metadata:
  name: dotnetapp
  labels:
    app: dotnetapp
spec:
  ports:
    - port: 80
  selector:
    app: dotnetapp
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dotnetapp
  labels:
    app: dotnetapp
spec:
  selector:
    matchLabels:
      app: dotnetapp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dotnetapp
        tier: frontend
    spec:
      containers:
      - name: docker-compose-dotnet-core-and-mssql-app
        image: 381492085613.dkr.ecr.us-east-1.amazonaws.com/demo:docker-compose-dotnet-core-and-mssql-app
        ports:
        - containerPort: 80
